### ISSUE TITLE
Error on _hdaServer.Connect

### ISSUE THREAD

**Issue by zlatinejc** [jdecuyper/OPC-HDA-Client#1]
I cannot get your code to run.
I am running Matrikon simulation server, on Win 8 with VS 2015.
Don't ask me about the OPC redistributables cause I do not know how to install them successfully on my system.

![image](https://cloud.githubusercontent.com/assets/10756198/16839476/87ce9162-49cf-11e6-912a-7e477de3698b.png)

Thanks for your time.

**Comment by jdecuyper** [comment]
You need to add the OPC assemblies to your bin folder. You can get them from the OPC portal or share me your email so I can send them to you.

**Comment by jdecuyper** [comment]
Actually, you can download the assemblies [directly from the OPC Foundation website](https://opcfoundation.org/developer-tools/developer-kits-classic/core-components/). You only need to create an account.

**Comment by zlatinejc** [comment]
Could you please send it to me anyways, cause I cannot get them installed via the OPC foundation account - tried gazilion times.

Email: zlatinejc@gmail.com
Tnx
